### ISSUE TITLE
(WIP) [Meta] Introduce Maplibre for Vector Tiles

### ISSUE THREAD

**Issue by tordans** [gravitystorm/openstreetmap-website#289]
Hey @gravitystorm I think I remember that you use this ticket list here to draft issues that are not ready for the main repo, yet. I thought I'd share my WIP notes on potential tickets on a migration to Maplibre. They are not finished, but might be a start for you. Feel free to reuse what you need or remove it all…
I drafted it as a set of separate tickets, but they are all in one big list below to make re-arranging the pieces easier.

---
---
---

# [Meta] Introduce Maplibre for Vector Tiles

## Context

2024 was announced to be [the year OSM embraces vector tiles](https://blog.openstreetmap.org/2024/02/11/2024-announcing-the-year-of-the-openstreetmap-vector-maps/).

The data and map styles to showcase OSM data with minutely updates is being worked on right now.

What can and should we do on the website front to present this now style and data in the best way possible?

### Maplibre GL JS

Right now, the OSM website tiles are rendered using Leaflet. Leaflet is great for rendering pixel based maps.

For vector tiles, MapLibre GL JS is more commonly used and provides more features that are focussed on vector data.

It would be possible to integrate the new vector tiles using Leaflet, which is what is being done in https://github.com/openstreetmap/openstreetmap-website/pull/__NOPING__4042.

However, we want to take this opportunity to evaluat updating our rendering library to a library that is focussed on vector tiles first.

### Process

This ticket a meta ticket to collect glue together small, actionable tickets together. 

## Subtickets

- [ ] Migrate user home location map to MapLibre

---
---
---

# Migrate user home location map to MapLibre

## Context

See #META_TICKET_ID

The page https://www.openstreetmap.org/profile/edit has a map with some interaction to position a location pin.

It is a good candidate to test out switching to Maplibre GL JS in a contained environment.

The goal is to learn about how to integrate Maplibre GL JS into the website and later use this knowledge and code to improve other areas of the website.

## Goal

Replace the current map and functionality with Maplibre GL JS, preserving the current feature set.

## TBD

- [ ] Which OSM Vector tiles dataset should be used for this? (Data source and map style)

---

# Setup a test page for Maplibre GL JS

## Context

See #META_TICKET_ID

In order to iterate on a possible migration to Maplibre GL JS, we want a way to iterate and test the new technical setup.

## Goal

Add openstreetmap.org/maplibre as a copy of the main map using Maplibre GL JS.

This page will be discontinued at some point and at this point redirect to the main map.

The gaol of this ticket is to find a good setup to manage the files in the repo. Migrating specific features should be managed in separate issues.

## List of features that need to be migrated

- [ ] Locate me
- [ ] Show context menu for right click
- [ ] Context menu: Add route action (from/to)
- [ ] Context menu: Add new note action
- [ ] Context menu: Add show address action
- [ ] Context menu: Add center map action
- [ ] Context menu: Add map object action
- [ ] Notes layer (show points and interaction)
- [ ] Map data layer (show data and interaction)
- [ ] Toggle base map

> [!INFO]
> ^--- this is where I stopped writing. My idea was, to have further separate issues for all the items in this list (once the list is scoped well). And then maybe have the same list inside the META ticket? Or something like this…

**Comment by gravitystorm** [comment]
> Hey @gravitystorm I think I remember that you use this ticket list here to draft issues that are not ready for the main repo, yet

Sort of! It's more like a personal todo list, particularly if there's something that I want to look into (e.g. a new gem, or some refactoring) but I'm not sure it's actually a good idea yet, or if it's something small were I want to remember to do it but it's not worth a full explanation on the main tracker.

I've been using it less more recently since the maintainer jobs mean I'm doing very little coding.

> I thought I'd share my WIP notes on potential tickets on a migration to Maplibre.

I think first we need a careful list of pros/cons for moving from Leaflet to Maplibre. Both libraries can support raster, both can support vector, so we can freely choose between them. As far as I'm aware the main (relevant to osm.org) difference with Maplibre is around fractional zooms - how does that interact with most of our layers being rasters? I don't have enough Maplibre experience to judge. Anything else that should be put into the comparison? Supported range of browsers? Performance for rasters/data layer? There's presumably some reasons why people still use Leaflet for standard raster maps, so what would we lose by switching to Maplibre for those?

**Comment by 1ec5** [comment]
Hey, I just noticed this issue – glad both of you have done some thinking about it. @tordans and I chatted briefly this morning. Here are some initial thoughts, as someone who helped build MapLibre’s predecessor and helps to maintain a fork that partly implements this idea already.

> Both libraries can support raster, both can support vector, so we can freely choose between them.

Unlike OpenLayers, Leaflet doesn’t support vector tiles natively; you need to install MapLibre GL&nbsp;JS sort of headlessly and use [maplibre-gl-leaflet](https://github.com/maplibre/maplibre-gl-leaflet/) as a compatibility shim. OpenHistoricalMap’s very lightweight fork of this project has already taken this approach. (We had to because the main use case is manipulating an interactive time slider, which dynamically filters vector tiles that contain all of history commingled together. It wouldn’t’ve been feasible to generate a whole planet of raster tiles for each day in history.)

maplibre-gl-leaflet has been more or less working for us over the past few years, but we really want to wean ourselves off the compatibility shim: OpenHistoricalMap/issues#651 OpenHistoricalMap/issues#828. The plugin tends to be pretty janky when you’re working with heavy tiles. Sometimes tiles will load but Leaflet won’t update due to what appears to be a race condition. It’s also pretty wasteful: here we’re loading a much more complex library than Leaflet in order to perform the rendering locally, but then we put it behind Leaflet and forego much of the flexibility we just loaded into memory.

> As far as I'm aware the main (relevant to osm.org) difference with Maplibre is around fractional zooms - how does that interact with most of our layers being rasters? I don't have enough Maplibre experience to judge.

MapLibre GL&nbsp;JS supports raster tiles too. Unless you disable incremental zooming, it’ll interpolate between zoom levels, which results in slight blurriness. The behavior was optimized for raster imagery such as aerial imagery, where reading comprehension is irrelevant. But personally I’m not too bothered by the overzooming. It’s probably more noticeable to those of us who are very familiar with Leaflet, but not to more casual users and mappers. You can try it for yourself by opening [geojson.io](https://geojson.io/#map=8.23/36.17/-86.214) and switching to “OSM” (OSM Carto) in the lower-left corner.

Admittedly, incremental zooming tends to bug my OCD around seeing a decimal zoom level in the URL. 😉

> Supported range of browsers?

MapLibre GL&nbsp;JS requires newer browsers than Leaflet. Leaflet’s browser support matrix still lists Internet Explorer 9, whereas for instance maplibre/maplibre-gl-js#4560 requires at least Edge 12 / Firefox 46 / Chrome 50, and I generally can’t load any MapLibre map in SeaMonkey 2.53.20, which is equivalent to Firefox 128.0. I suspect usage of such old browsers is vanishingly small at this point, but probably a little more prevalent on Android devices in lower-income countries.

The bigger issue is that MapLibre GL&nbsp;JS requires WebGL. Even if the browser fully supports the WebGL API, there’s a chance the system might not support it due to an outdated graphics card. A few years ago, the conclusion in https://github.com/openstreetmap/openstreetmap-website/issues/2686#issuecomment-1226131786 was that we’d need to maintain maplibre-gl-leaflet as a fallback for the 8% of active mappers who use non-WebGL-capable devices. Maybe the share of such users has since fallen to the point where we don’t need to consider this possibility. But even if we keep maplibre-gl-leaflet around for this cohort, that doesn’t seem quite as bad as maintaining both raw Leaflet and raw MapLibre GL&nbsp;JS in parallel.

> There's presumably some reasons why people still use Leaflet for standard raster maps, so what would we lose by switching to Maplibre for those?

At this point, I think people mainly use Leaflet for its simplicity. If you just need to show a small locator map with a pin and popup on it, MapLibre GL&nbsp;JS is definitely overkill – maybe Leaflet too.

If you only have raster tiles to show, then those tiles limit the value that MapLibre can add to the user experience. But we’re on the cusp of publishing vector tiles, presumably to the same wide audience as our raster tiles. It would make little sense to publish something we can’t dogfood on our own site.

For now, maplibre-gl-leaflet would be a low-risk step in the right direction. But we need to plan for a future beyond this shim. Beyond backwards compatibility, we also need to consider the real and potential upsides from migrating to a vector tile–capable renderer. I can think of a few things off the top of my head that are exciting but still need to be discussed with the community, since there are tradeoffs:

* Higher zoom levels – Vector styles will be able to go well beyond the current maximum zoom level, revealing many POIs and other details that currently collide each other out at z19 without requiring style designers to accommodate excessive label density.
* Label localization – Engage mappers around the world who speak minority languages. Help the community monitor changes to `name:*=*` tags, which are ironically prominent in most third-party data consumers but hidden in our mapping community’s own workspace.
* Dark mode – Some featured styles can support dark mode without going through the trouble of designing a whole new style.
* Globe view – As an option, this would improve OSM’s pedagogical value and our reputation in some regions of the world.
* Vector tile inspection – Ordinary mappers need to be able to see the impact of their changes on the vector tiles and potentially debug any anomalies in feature properties. The Shortbread schema is abstracted away from the raw tagging schema, so the map data overlay and Overpass querying don’t meet this need.
* Feature selection – If the user can click on a POI to reveal some basic details about it, saving a trip to Overpass, then style designers will feel less pressure to cram these details into [inscrutable symbology](https://imagico.de/blog/en/the-world-of-parking-2-new-visualization-ideas/).

> In order to iterate on a possible migration to Maplibre GL JS, we want a way to iterate and test the new technical setup.

For a future migration to MapLibre without Leaflet, I hereby offer up OpenHistoricalMap as sacrifice. OHM’s much smaller audience has a much higher tolerance for experimentation. We deploy to production weekly and to staging at least as often. Merges from upstream are less frequent. I could see us using OHM to build out a rough implementation, then upstream it to OSM for fit and finish.
